apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-saksbehandling-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-saksbehandling-frontend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /api/internal/isAlive
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /api/internal/isReady
    initialDelay: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /api/internal/metrics
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - {{ingress}}
  env:
    - name: SELF_URL
      value: {{ingress}}
    - name: GCP_ENV
      value: {{gcp_env}}
    - name: DP_BEHANDLING_URL
      value: {{dp-behandling_url}}
    - name: DP_SAKSBEHANDLING_URL
      value: {{dp-saksbehandling_url}}
    - name: DP_MELDING_OM_VEDTAK_URL
      value: {{dp-melding-om-vedtak_url}}
    - name: SAF_URL
      value: {{saf_url}}
    - name: DP_SOKNAD_ORKESTRATOR_URL
      value: {{dp-soknad-orkestrator_url}}
    - name: ARBEID_INNTEKT_URL
      value: {{arbeid_inntekt_url}}
    - name: GOSYS_URL
      value: {{gosys_url}}
    - name: MODIA_URL
      value: {{modia_url}}
    - name: MELDEKORT_URL
      value: {{meldekort_url}}
    - name: INNTEKTREDIGERING_URL
      value: {{inntektredigering_url}}
    - name: GRISEN_URL
      value: {{grisen_url}}
    - name: DAGPENGER_NORGE_URL
      value: {{dagpenger-norge_url}}
    - name: SAF_AUDIENCE
      value: {{saf_audience}}
    - name: PDL_AUDIENCE
      value: {{PDL_audience}}

    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_METRICS_ENABLED
      value: "true"
    - name: OTEL_METRICS_EXEMPLAR_FILTER
      value: ALWAYS_ON

    - name: UNLEASH_SERVER_API_URL
      value: {{unleash.url}}

    - name: FARO_URL
      value: {{faro_url}}
    - name: GITHUB_SHA
      value: {{githubSha}}

  envFrom:
    - secret: dp-saksbehandling-frontend-unleash-api-token


  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: aura
    outbound:
      external:
        - host: graph.microsoft.com
        - host: login.microsoftonline.com
        - host: saf.dev-fss-pub.nais.io
        - host: saf.prod-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: dagpenger-unleash-api.nav.cloud.nais.io

      rules:
        - application: dp-saksbehandling
        - application: dp-behandling
        - application: dp-melding-om-vedtak
        - application: dp-soknad-orkestrator

  azure:
    application:
      tenant: {{azure.tenant}}
      enabled: true
      claims:
        groups:
          - id: {{azure.grupper.saksbehandler}}
          - id: {{azure.grupper.beslutter}}
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic

  frontend:
    generatedConfig:
      mountPath: /app/build/client/nais.js

