apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-saksbehandling-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-saksbehandling-frontend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "{{base_path}}/api/internal/isalive"
    initialDelay: 3
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "{{base_path}}/api/internal/isready"
    initialDelay: 3
    timeout: 1
  prometheus:
    enabled: true
    path: "{{base_path}}/api/internal/metrics"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - {{ingress}}
  env:
    - name: SELF_URL
      value: {{ingress}}
    - name: BASE_PATH
      value: {{base_path}}
    - name: DP_BEHANDLING_URL
      value: {{dp-behandling_url}}
    - name: DP_RAPPORTERING_URL
      value: http://dp-rapportering
  accessPolicy:
    outbound:
      external:
        - host: {{dp-behandling_host}}
        - host: {{dp-rapportering_host}}
        - host: graph.microsoft.com
        - host: login.microsoftonline.com
        - host: saf.dev-fss-pub.nais.io
        - host: rt6o382n.apicdn.sanity.io
      rules: 
        - application: dp-rapportering
      
  azure:
    application:
      tenant: trygdeetaten.no
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
