apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-saksbehandling-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-saksbehandling-frontend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "{{base_path}}/api/internal/isalive"
    initialDelay: 3
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "{{base_path}}/api/internal/isready"
    initialDelay: 3
    timeout: 1
  prometheus:
    enabled: true
    path: "{{base_path}}/api/internal/metrics"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 128Mi
  ingresses:
    - {{ingress}}
  env:
    - name: SELF_URL
      value: {{ingress}}
    - name: BASE_PATH
      value: {{base_path}}
    - name: DP_BEHANDLING_URL
      value: {{dp-behandling_url}}
  azure:
    application:
      tenant: nav.no
      enabled: true
      claims:
        groups:
          - id: 4edb2ce5-4f0e-4f6f-9b82-b8e75e9dd09e # teamdagpenger
          - id: 57b411c7-c876-47db-a4a5-e33cddecdacf # meldeplikt
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
