apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: dp-saksbehandling-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-saksbehandling-frontend
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: teamdagpenger
  secretName: dp-saksbehandling-frontend-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: {{unleash.environment}}