/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/innsending/{behandlingId}/ferdigstill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Ferdigstill innsending for en gitt id */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    behandlingId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FerdigstillInnsendingRequest"];
                };
            };
            responses: {
                /** @description Innsending ferdigstilt */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Innsending informasjon for behandlingId ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/innsending/{behandlingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hent innsending for en gitt id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    behandlingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vellykket respons med innsending */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Innsending"];
                    };
                };
                /** @description Innsending informasjon for behandlingId ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hent alle oppgaver med status Klar til behandling */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Filtrer på rettighetsknagger (f.eks. "Ordinær", "Verneplikt", "Permittert")
                     * @example [
                     *       "Ordinær",
                     *       "Verneplikt"
                     *     ]
                     */
                    rettighet?: string[];
                    /**
                     * @description Filtrer på søknadsresultatknagger (f.eks. "Avslag", "Innvilgelse")
                     * @example [
                     *       "Avslag",
                     *       "Innvilgelse"
                     *     ]
                     */
                    soknadsresultat?: string[];
                    /**
                     * @description Filtrer på avslagsgrunner (f.eks. "Minsteinntekt", "Arbeidstid")
                     * @example [
                     *       "Minsteinntekt"
                     *     ]
                     */
                    avslagsgrunn?: string[];
                    /**
                     * @description Filtrer på gjenopptakknagger
                     * @example [
                     *       "Gjenopptak"
                     *     ]
                     */
                    gjenopptak?: string[];
                    /**
                     * @description Filtrer på på-vent årsaker (f.eks. "Avvent svar", "Avvent dokumentasjon")
                     * @example [
                     *       "Avvent svar"
                     *     ]
                     */
                    paa_vent?: string[];
                    /**
                     * @description Filtrer på avbruddsårsaker
                     * @example [
                     *       "Trukket søknad"
                     *     ]
                     */
                    avbrutt_grunn?: string[];
                    /** @description Filtrer på ettersendinger */
                    ettersending?: string[];
                    tilstand?: components["schemas"]["OppgaveTilstand"][];
                    utlostAv?: components["schemas"]["UtlostAvType"][];
                    fom?: string;
                    tom?: string;
                    mineOppgaver?: boolean;
                    antallOppgaver?: number;
                    side?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vellykket respons med en liste over oppgaver */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OppgaveOversiktResultat"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave/neste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Hent neste oppgave og tildel denne til saksbehandler */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NesteOppgave"];
                };
            };
            responses: {
                /** @description Vellykket respons med detaljer om oppgaven som tildeles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Oppgave"];
                    };
                };
                /** @description Ingen flere oppgaver å behandle akkurat nå */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave/{oppgaveId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hent en oppgave ved hjelp av dens ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    oppgaveId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vellykket respons med detaljer om oppgaven */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Oppgave"];
                    };
                };
                /** @description Oppgaven ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave/{oppgaveId}/notat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Legg til et notat på en oppgave */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    oppgaveId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NotatRequest"];
                };
            };
            responses: {
                /** @description Notatet ble lagt til */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LagreNotatResponse"];
                    };
                };
                /** @description Oppgaven ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Notat kan ikke lagres på oppgaven i denne tilstanden */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        /** Slett notat på en oppgave */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    oppgaveId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notatet slettet */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LagreNotatResponse"];
                    };
                };
                /** @description Oppgaven ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Notat kan ikke slettes fra oppgaven i denne tilstanden */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave/{oppgaveId}/kontrollert-brev": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Beslutter kvitterer ut at brev er kontrollert i gosys */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    oppgaveId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["KontrollertBrevRequest"];
                };
            };
            responses: {
                /** @description Flagg for kontrollert brev er lagret */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Feil ved parsing av request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Oppgaven ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Oppgaven kan ikke endre kontrollertBrev i denne tilstanden */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave/{oppgaveId}/melding-om-vedtak-kilde": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Endre kilde for melding om vedtak */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    oppgaveId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MeldingOmVedtakKildeRequest"];
                };
            };
            responses: {
                /** @description Kilde for melding om vedtak er lagret */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Oppgaven ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Oppgaven kan ikke endre kilde for melding om vedtak i denne tilstanden */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave/{oppgaveId}/send-til-kontroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Saksbehandler sender oppgaven til kontroll og innstiller vedtaket */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    oppgaveId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vellykket respons */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Oppgaven ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Oppgaven kan ikke sendes til kontroll i denne tilstanden */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave/{oppgaveId}/returner-til-saksbehandler": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Beslutter sender oppgaven tilbake til saksbehandler */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    oppgaveId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vellykket respons */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Oppgaven ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Oppgaven kan ikke returneres til saksbehandler i denne tilstanden */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave/{oppgaveId}/avbryt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Avbryter en oppgave. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    oppgaveId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AvbrytOppgave"];
                };
            };
            responses: {
                /** @description Oppgaven er avbrutt */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Oppgaven ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Oppgaven kan ikke avbrytes i denne tilstanden */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave/{oppgaveId}/ferdigstill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Ferdigstill en Oppgave ved å godkjenne behandlingen og starte utsending. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    oppgaveId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Oppgaven er ferdig behandlet og utsending av melding om vedtak har startet */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Oppgaven ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Oppgaven kan ikke ferdigstilles i denne tilstanden */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave/{oppgaveId}/utsett": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Saksbehandler utsetter oppgaven */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    oppgaveId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UtsettOppgave"];
                };
            };
            responses: {
                /** @description Vellykket respons */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Oppgaven ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Oppgaven kan ikke utsettes i denne tilstanden */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave/{oppgaveId}/tildel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Saksbehandler blir tildelt ansvaret for oppgaven */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    oppgaveId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returnerer oppdatert tilstand etter tildeling av oppgave til saksbehandler eller beslutter */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TildeltOppgave"];
                    };
                };
                /** @description Oppgaven ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Oppgaven kan ikke tildeles i denne tilstanden */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oppgave/{oppgaveId}/legg-tilbake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Saksbehandler/beslutter fjernes som ansvarlig for oppgaven, og oppgaven går tilbake til oppgavelisten */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    oppgaveId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fjernet saksbehandler/beslutter som ansvarlig for oppgaven, og oppgaven gjøres klar til behandling/kontroll */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Oppgaven ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Oppgaven kan ikke legges tilbake i oppgavelisten igjen */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/klage/opprett": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Oppretter en klage fra en applikasjon (p.t. dp-mottak) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OpprettKlage"];
                };
            };
            responses: {
                /** @description Vellykket oppretting av klage og tilhørende oppgave */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OppgaveOversikt"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/klage/opprett-manuelt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Oppretter en klage fra saksbehandler */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OpprettKlage"];
                };
            };
            responses: {
                /** @description Vellykket oppretting av klage og tilhørende oppgave */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OppgaveOversikt"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/klage/{behandlingId}/opplysning/{opplysningId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Oppdaterer opplysning i klage */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    behandlingId: string;
                    opplysningId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OppdaterKlageOpplysning"];
                };
            };
            responses: {
                /** @description Vellykket oppdatering av opplysning i klage */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Klagen eller opplysningen ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/klage/{behandlingId}/ferdigstill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Ferdigstill klage */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    behandlingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Klagen er ferdigbehandlet */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Klagen ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/klage/{behandlingId}/trekk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Trekk klage */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    behandlingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Klagen er trukket */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Klagen ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/klage/{behandlingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hent klage basert på behandlingId til klagen */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    behandlingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vellykket respons med detaljer om klagen */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Klage"];
                    };
                };
                /** @description Klagen ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/person/personId": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hent personId basert på personIdent */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PersonIdent"];
                };
            };
            responses: {
                /** @description Vellykket respons med personinformasjon */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonId"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/person/{personId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hent personinformasjon basert på UUID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    personId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vellykket respons med personinformasjon */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonOversikt"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/person/oppgaver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hent alle oppgaver til en person */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PersonIdent"];
                };
            };
            responses: {
                /** @description Vellykket respons med en liste over oppgaver som samsvarer med ident */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OppgaveOversikt"][];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandling/{behandlingId}/oppgaveId": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Henter oppgaveId basert på en behandlingId */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    behandlingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fant oppgaveId for behandlingId */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OppgaveId"];
                    };
                };
                /** @description OppgaveId for behandlingId ble ikke funnet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/behandling/{behandlingId}/sakId": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Henter sakId basert på en behandlingId */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    behandlingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fant sakId for behandlingId */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                /** @description Fant ikke sakId for behandlingId */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/statistikk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hent statistikk for oppgaver
         * @description Henter statistikk for oppgaver.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Filtrer på rettighet-emneknagger (f.eks. "Ordinær", "Verneplikt", "Permittert")
                     * @example [
                     *       "Ordinær",
                     *       "Verneplikt",
                     *       "Permittert"
                     *     ]
                     */
                    rettighet?: string[];
                    tilstand?: components["schemas"]["OppgaveTilstand"][];
                    utlostAv?: components["schemas"]["UtlostAvType"][];
                    fom?: string;
                    tom?: string;
                    grupperEtter?: components["schemas"]["GrupperEtter"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistikk hentet */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatistikkV2"];
                    };
                };
                /** @description Uautorisert tilgang */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hent statistikk
         * @description Henter statistikk for innlogget saksbehandler samt generell statistikk.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistikk hentet */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            individuellStatistikk: components["schemas"]["Statistikk"];
                            generellStatistikk: components["schemas"]["Statistikk"];
                            beholdningsinfo: components["schemas"]["BeholdningsInfo"];
                        };
                    };
                };
                /** @description Uautorisert tilgang */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
                /** @description Feil */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpProblem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Innsending: {
            /** Format: uuid */
            behandlingId: string;
            journalpostId: string;
            lovligeSaker: components["schemas"]["TynnSak"][];
            /** Format: uuid */
            sakId?: string;
            vurdering?: string;
            nyBehandling?: components["schemas"]["TynnBehandling"];
        };
        TynnSak: {
            /** Format: uuid */
            sakId: string;
            /** Format: date-time */
            opprettetDato: string;
        };
        TynnBehandling: {
            /** Format: uuid */
            behandlingId: string;
            behandlingType: components["schemas"]["BehandlingType"];
        };
        Person: {
            ident: string;
            /** Format: uuid */
            id: string;
            fornavn: string;
            etternavn: string;
            mellomnavn?: string;
            /** Format: date */
            fodselsdato: string;
            alder: number;
            statsborgerskap?: string;
            kjonn: components["schemas"]["Kjonn"];
            skjermesSomEgneAnsatte: boolean;
            adressebeskyttelseGradering: components["schemas"]["AdressebeskyttelseGradering"];
            sikkerhetstiltak: components["schemas"]["Sikkerhetstiltak"][];
        };
        PersonOversikt: {
            person: components["schemas"]["Person"];
            saker: components["schemas"]["Sak"][];
            oppgaver: components["schemas"]["OppgaveOversikt"][];
        };
        Sak: {
            /** Format: uuid */
            id: string;
            behandlinger: components["schemas"]["Behandling"][];
        };
        Behandling: {
            /** Format: uuid */
            id: string;
            behandlingType: components["schemas"]["BehandlingType"];
            utlostAv: components["schemas"]["UtlostAvType"];
            /** Format: date-time */
            opprettet: string;
            /** Format: uuid */
            oppgaveId?: string;
        };
        OppgaveOversiktResultat: {
            oppgaver: components["schemas"]["OppgaveOversikt"][];
            totaltAntallOppgaver: number;
        };
        OppgaveOversikt: {
            /** Format: uuid */
            oppgaveId: string;
            /** Format: uuid */
            behandlingId: string;
            personIdent: string;
            behandlerIdent?: string;
            /** Format: date-time */
            tidspunktOpprettet: string;
            behandlingType: components["schemas"]["BehandlingType"];
            utlostAv: components["schemas"]["UtlostAvType"];
            emneknagger: components["schemas"]["Emneknagg"][];
            skjermesSomEgneAnsatte: boolean;
            adressebeskyttelseGradering: components["schemas"]["AdressebeskyttelseGradering"];
            tilstand: components["schemas"]["OppgaveTilstand"];
            lovligeEndringer?: components["schemas"]["LovligeEndringer"];
            /** Format: date */
            utsattTilDato?: string;
        };
        Oppgave: {
            /** Format: uuid */
            oppgaveId: string;
            /** Format: uuid */
            behandlingId: string;
            saksbehandler?: components["schemas"]["Behandler"];
            beslutter?: components["schemas"]["Behandler"];
            person: components["schemas"]["Person"];
            /** Format: date-time */
            tidspunktOpprettet: string;
            behandlingType: components["schemas"]["BehandlingType"];
            utlostAv: components["schemas"]["UtlostAvType"];
            /** Format: date */
            utsattTilDato?: string;
            journalpostIder: string[];
            historikk: components["schemas"]["OppgaveHistorikk"][];
            emneknagger: components["schemas"]["Emneknagg"][];
            tilstand: components["schemas"]["OppgaveTilstand"];
            notat?: components["schemas"]["Notat"];
            lovligeEndringer: components["schemas"]["LovligeEndringer"];
            /** Format: uuid */
            soknadId?: string;
            meldingOmVedtakKilde: components["schemas"]["MeldingOmVedtakKilde"];
            kontrollertBrev: components["schemas"]["KontrollertBrev"];
        };
        /** @enum {string} */
        GrupperEtter: "RETTIGHETSTYPE" | "OPPGAVETYPE";
        /** @enum {string} */
        Kjonn: "MANN" | "KVINNE" | "UKJENT";
        KontrollertBrevRequest: {
            kontrollert: components["schemas"]["KontrollertBrev"];
        };
        /** @enum {string} */
        KontrollertBrev: "JA" | "NEI" | "IKKE_RELEVANT";
        MeldingOmVedtakKildeRequest: {
            meldingOmVedtakKilde?: components["schemas"]["MeldingOmVedtakKilde"];
        };
        /** @enum {string} */
        MeldingOmVedtakKilde: "DP_SAK" | "GOSYS" | "INGEN";
        /**
         * @description Emneknagg med visningsnavn og kategori.
         *     Når du filtrerer oppgaver med query parameter 'emneknagg', bruk kun visningsnavnet (string).
         *     Responsen vil returnere fulle Emneknagg-objekter med både visningsnavn og kategori.
         */
        Emneknagg: {
            /**
             * @description Det lesbare navnet på emneknaggen (f.eks. "Avslag", "Innvilgelse")
             * @example Avslag
             */
            visningsnavn: string;
            kategori: components["schemas"]["EmneknaggKategori"];
        };
        /**
         * @description Kategorisering av emneknagger for enklere gruppering og filtrering i frontend
         * @enum {string}
         */
        EmneknaggKategori: "RETTIGHET" | "GJENOPPTAK" | "SOKNADSRESULTAT" | "AVSLAGSGRUNN" | "AVBRUTT_GRUNN" | "PAA_VENT" | "ETTERSENDING" | "UDEFINERT";
        /** @enum {string} */
        OppgaveTilstand: "KLAR_TIL_BEHANDLING" | "UNDER_BEHANDLING" | "KLAR_TIL_KONTROLL" | "UNDER_KONTROLL" | "FERDIG_BEHANDLET" | "PAA_VENT" | "AVVENTER_LÅS_AV_BEHANDLING" | "AVVENTER_OPPLÅSING_AV_BEHANDLING" | "AVBRUTT" | "AVBRUTT_MASKINELT";
        /** @enum {string} */
        UtlostAvType: "KLAGE" | "MELDEKORT" | "SØKNAD" | "MANUELL" | "INNSENDING";
        /** @enum {string} */
        BehandlingType: "RETT_TIL_DAGPENGER" | "KLAGE" | "INNSENDING";
        LovligeEndringer: {
            /** @description Årsaker til at oppgaven settes på vent */
            paaVentAarsaker: components["schemas"]["UtsettOppgaveAarsak"][];
            /** @description Årsaker til at oppgaven avbrytes */
            avbrytAarsaker: components["schemas"]["AvbrytOppgaveAarsak"][];
        };
        /** @enum {string} */
        AdressebeskyttelseGradering: "UGRADERT" | "FORTROLIG" | "STRENGT_FORTROLIG" | "STRENGT_FORTROLIG_UTLAND";
        Sikkerhetstiltak: {
            beskrivelse: string;
            /** Format: date */
            gyldigTom: string;
        };
        PersonIdent: {
            ident: string;
        };
        PersonId: {
            /** Format: uuid */
            id: string;
        };
        OppgaveId: {
            /** Format: uuid */
            oppgaveId: string;
        };
        OppgaveHistorikk: {
            /** @enum {string} */
            type: "notat" | "statusendring";
            /** Format: date-time */
            tidspunkt: string;
            tittel: string;
            behandler: {
                navn: string;
                /** @enum {string} */
                rolle?: "saksbehandler" | "beslutter" | "system";
            };
            body?: string;
        };
        NesteOppgave: {
            queryParams: string;
        };
        AvbrytOppgave: {
            aarsak: components["schemas"]["AvbrytOppgaveAarsak"];
        };
        /** @enum {string} */
        AvbrytOppgaveAarsak: "BEHANDLES_I_ARENA" | "FLERE_SØKNADER" | "TRUKKET_SØKNAD" | "ANNET";
        UtsettOppgave: {
            /** Format: date */
            utsettTilDato: string;
            beholdOppgave: boolean;
            aarsak: components["schemas"]["UtsettOppgaveAarsak"];
        };
        /** @enum {string} */
        UtsettOppgaveAarsak: "AVVENT_SVAR" | "AVVENT_DOKUMENTASJON" | "AVVENT_MELDEKORT" | "AVVENT_PERMITTERINGSÅRSAK" | "AVVENT_RAPPORTERINGSFRIST" | "AVVENT_SVAR_PÅ_FORESPØRSEL" | "ANNET";
        LagreNotatResponse: {
            /**
             * Format: date-time
             * @description Tidspunkt notat sist ble endret
             */
            sistEndretTidspunkt: string;
        };
        NotatRequest: {
            tekst: string;
        };
        Notat: {
            tekst: string;
            /**
             * Format: date-time
             * @description Tidspunkt notat sist ble endret
             */
            sistEndretTidspunkt: string;
        };
        Behandler: {
            ident: string;
            fornavn: string;
            etternavn: string;
            enhet: {
                navn: string;
                enhetNr: string;
                postadresse: string;
            };
        };
        Statistikk: {
            /**
             * @description Antall behandlede oppgaver i løpet av dagen.
             * @default 0
             * @example 5
             */
            dag: number;
            /**
             * @description Antall behandlede oppgaver i løpet av uken.
             * @default 0
             * @example 30
             */
            uke: number;
            /**
             * @description Totalt antall behandlede oppgaver.
             * @default 0
             * @example 200
             */
            totalt: number;
        };
        StatistikkV2: {
            grupper: components["schemas"]["StatistikkV2Gruppe"][];
            serier: components["schemas"]["StatistikkV2Serie"][];
            resultat: components["schemas"]["StatistikkV2Resultat"];
        };
        StatistikkV2Gruppe: {
            navn: string;
            total: number;
            /** Format: date-time */
            eldsteOppgave?: string;
        };
        StatistikkV2Serie: {
            navn: string;
            total: number;
        };
        StatistikkV2Resultat: {
            grupper: components["schemas"]["V2StatusNavn"][];
            serier: components["schemas"]["V2Serie"][];
        };
        V2StatusNavn: {
            navn: string;
        };
        V2Serie: {
            navn: string;
            verdier: components["schemas"]["V2GruppeMedAntall"][];
        };
        V2GruppeMedAntall: {
            gruppe: string;
            antall: number;
        };
        BeholdningsInfo: {
            /**
             * @description Antall oppgaver som er klar til behandling
             * @default 0
             */
            antallOppgaverKlarTilBehandling: number;
            /**
             * @description Antall oppgaver som er klar til kontroll
             * @default 0
             */
            antallOppgaverKlarTilKontroll: number;
            /**
             * Format: date-time
             * @description Dato for eldste oppgave som er klar til behandling
             */
            datoEldsteUbehandledeOppgave?: string;
        };
        TildeltOppgave: {
            nyTilstand: components["schemas"]["OppgaveTilstand"];
            behandlingType: components["schemas"]["BehandlingType"];
            utlostAv: components["schemas"]["UtlostAvType"];
        };
        Klage: {
            /** Format: uuid */
            behandlingId: string;
            saksbehandler?: components["schemas"]["Behandler"];
            behandlingOpplysninger: components["schemas"]["KlageOpplysning"][];
            utfallOpplysninger: components["schemas"]["KlageOpplysning"][];
            utfall: components["schemas"]["Utfall"];
        };
        TekstVerdi: {
            verdi: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "TEKST" | "LISTEVALG";
        };
        BoolskVerdi: {
            verdi: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "BOOLSK";
        };
        DatoVerdi: {
            /** Format: date */
            verdi: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DATO";
        };
        ListeVerdi: {
            verdi: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "FLER_LISTEVALG";
        };
        OpprettKlage: {
            /** Format: date-time */
            opprettet: string;
            journalpostId: string;
            /** Format: uuid */
            sakId: string;
            personIdent: components["schemas"]["PersonIdent"];
        };
        OppdaterKlageOpplysning: components["schemas"]["TekstVerdi"] | components["schemas"]["BoolskVerdi"] | components["schemas"]["DatoVerdi"] | components["schemas"]["ListeVerdi"];
        /** @enum {string} */
        KlageGruppe: "FORMKRAV" | "KLAGESAK" | "FRIST" | "KLAGE_ANKE";
        KlageOpplysningTekst: {
            /** Format: uuid */
            opplysningId: string;
            opplysningNavnId: string;
            navn: string;
            paakrevd: boolean;
            gruppe: components["schemas"]["KlageGruppe"];
            valgmuligheter: string[];
            redigerbar: boolean;
            verdi?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "TEKST";
        };
        KlageOpplysningBoolsk: {
            /** Format: uuid */
            opplysningId: string;
            opplysningNavnId: string;
            navn: string;
            paakrevd: boolean;
            gruppe: components["schemas"]["KlageGruppe"];
            valgmuligheter: string[];
            redigerbar: boolean;
            verdi?: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "BOOLSK";
        };
        KlageOpplysningDato: {
            /** Format: uuid */
            opplysningId: string;
            opplysningNavnId: string;
            navn: string;
            paakrevd: boolean;
            gruppe: components["schemas"]["KlageGruppe"];
            valgmuligheter: string[];
            redigerbar: boolean;
            /** Format: date */
            verdi?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DATO";
        };
        KlageOpplysningFlerListeValg: {
            /** Format: uuid */
            opplysningId: string;
            opplysningNavnId: string;
            navn: string;
            paakrevd: boolean;
            gruppe: components["schemas"]["KlageGruppe"];
            valgmuligheter: string[];
            redigerbar: boolean;
            verdi?: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "FLER_LISTEVALG";
        };
        KlageOpplysningListeValg: {
            /** Format: uuid */
            opplysningId: string;
            opplysningNavnId: string;
            navn: string;
            paakrevd: boolean;
            gruppe: components["schemas"]["KlageGruppe"];
            valgmuligheter: string[];
            redigerbar: boolean;
            verdi?: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "LISTEVALG";
        };
        /** @enum {string} */
        KlageOpplysningType: "TEKST" | "BOOLSK" | "DATO" | "LISTEVALG" | "FLER_LISTEVALG";
        KlageOpplysning: components["schemas"]["KlageOpplysningTekst"] | components["schemas"]["KlageOpplysningBoolsk"] | components["schemas"]["KlageOpplysningDato"] | components["schemas"]["KlageOpplysningListeValg"] | components["schemas"]["KlageOpplysningFlerListeValg"];
        Utfall: {
            /** @enum {string} */
            verdi: "AVVIST" | "OPPRETTHOLDELSE" | "DELVIS_MEDHOLD" | "MEDHOLD" | "IKKE_SATT";
            /** @description Tilgjengelige utfall for klagebehandling */
            tilgjengeligeUtfall: string[];
        };
        FerdigstillInnsendingRequest: {
            /** Format: uuid */
            sakId?: string;
            vurdering: string;
            behandlingType?: components["schemas"]["BehandlingType"];
        };
        HttpProblem: {
            type: string;
            title: string;
            /** Format: int32 */
            status: number;
            detail?: string;
            instance: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
