/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/opplysninger/barn/{soknadbarnId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hent opplysning om barn */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description id for hele listen med barn på en gitt søknad, tilsvarende inntektId */
                    soknadbarnId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BarnResponse"][];
                    };
                };
                /** @description SøknadId mangler eller har feil format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Legg til nytt barn på søknad */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description id for hele listen med barn på en gitt søknad, tilsvarende inntektId */
                    soknadbarnId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BarnRequest"];
                };
            };
            responses: {
                /** @description Barn lagt til */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BarnResponse"][];
                    };
                };
                /** @description Ugyldig request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opplysninger/barn/{soknadbarnId}/{barnId}/slett": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Slett barn fra søknad */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description id for hele listen med barn på en gitt søknad, tilsvarende inntektId */
                    soknadbarnId: string;
                    /** @description id for det spesifikke barnet som skal slettes */
                    barnId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SlettBarnRequest"];
                };
            };
            responses: {
                /** @description Barn slettet */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Fant ikke barnet som skal slettes */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opplysninger/barn/{soknadbarnId}/{barnId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Oppdater opplysning om barn */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description id for hele listen med barn på en gitt søknad, tilsvarende inntektId */
                    soknadbarnId: string;
                    /** @description id for det spesifikke barnet som skal oppdateres */
                    barnId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BarnRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Opplysningen inneholder ingen endringer, kan ikke oppdatere */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description barnetilleggFom og barnetilleggTom må være satt når kvalifisererTilBarnetillegg er true */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Fant ikke barnet som skal oppdateres */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opplysninger/{soknadId}/barn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hent opplysning om barn
         * @deprecated
         * @description Deprekert! Bruk /opplysninger/barn/{soknadbarnId} i stedet
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    soknadId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BarnResponse"][];
                    };
                };
                /** @description SøknadId mangler eller har feil format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opplysninger/{soknadId}/barn/oppdater": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Oppdater opplysning om barn
         * @deprecated
         * @description Deprekert! Bruk /opplysninger/barn/{soknadbarnId} i stedet
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    soknadId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BarnRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Opplysningen inneholder ingen endringer, kan ikke oppdatere */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description barnetilleggFom og barnetilleggTom må være satt når kvalifisererTilBarnetillegg er true */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Fant ikke opplysningen som skal oppdateres */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/land": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hent liste med alle land */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Liste med land returnert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Land"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BarnOpplysning: {
            /** @enum {string} */
            id: "fornavnOgMellomnavn" | "etternavn" | "fodselsdato" | "oppholdssted" | "forsorgerBarnet" | "kvalifisererTilBarnetillegg" | "barnetilleggFom" | "barnetilleggTom" | "begrunnelse";
            /** Format: string */
            verdi: string;
            /** @enum {string} */
            dataType: "dato" | "land" | "boolsk" | "tekst";
            /** @enum {string} */
            kilde?: "soknad" | "register" | "saksbehandler";
        };
        BarnResponse: {
            /** Format: uuid */
            barnId: string;
            opplysninger: components["schemas"]["BarnOpplysning"][];
        };
        SlettBarnRequest: {
            /** Format: uuid */
            behandlingId: string;
            begrunnelse: string;
        };
        BarnRequest: {
            /** Format: uuid */
            behandlingId?: string;
            barn: components["schemas"]["BarnData"];
        };
        BarnData: {
            fornavnOgMellomnavn: string;
            etternavn: string;
            /** Format: date */
            fodselsdato: string;
            oppholdssted: string;
            forsorgerBarnet: boolean;
            kvalifisererTilBarnetillegg: boolean;
            /** Format: date */
            barnetilleggFom?: string;
            /** Format: date */
            barnetilleggTom?: string;
            begrunnelse: string;
        };
        Opplysning: {
            /** Format: uuid */
            opplysningId: string;
            "tekstn\u00F8kkel": string;
            type: components["schemas"]["Opplysningstype"];
            /** @description Svar kan være enten en string, boolean, dato eller periode (se Periodesvar) avhengig av hvilken type opplysning det er. */
            svar?: string | null;
            gyldigeSvar?: string[] | null;
        };
        /** @enum {string} */
        Opplysningstype: "land" | "periode" | "dato" | "tekst" | "boolean";
        Seksjon: {
            navn: components["schemas"]["Seksjonsnavn"];
            nesteUbesvarteOpplysning?: components["schemas"]["Opplysning"];
            besvarteOpplysninger: components["schemas"]["Opplysning"][];
            "erFullf\u00F8rt": boolean;
        };
        /** @enum {string} */
        Seksjonsnavn: "bostedsland";
        Periodesvar: {
            /** Format: date */
            fom: string;
            /** Format: date */
            tom?: string;
        };
        Land: {
            /** @example NOR */
            alpha3kode: string;
            /** @example Norge */
            navn: string;
        };
        HtmlDokument: {
            /** @description Skjemaet bruker har fylt som html, inkludert styling */
            html: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
