const norwegianCountryNames: Record<string, string> = {
  AFG: "Afghanistan",
  ALB: "Albania",
  DZA: "Algerie",
  ASM: "Amerikansk Samoa",
  AND: "Andorra",
  AGO: "Angola",
  AIA: "Anguilla",
  ATA: "Antarktika",
  ATG: "Antigua og Barbuda",
  ARG: "Argentina",
  ARM: "Armenia",
  ABW: "Aruba",
  AZE: "Aserbajdsjan",
  AUS: "Australia",
  BHS: "Bahamas",
  BHR: "Bahrain",
  BGD: "Bangladesh",
  BRB: "Barbados",
  AUT: "Østerrike",
  BEL: "Belgia",
  BLZ: "Belize",
  BEN: "Benin",
  BMU: "Bermuda",
  BTN: "Bhutan",
  BOL: "Bolivia",
  BES: "Bonaire, Sint Eustatius og Saba",
  BIH: "Bosnia-Hercegovina",
  BWA: "Botswana",
  BVT: "Bouvetøya",
  BRA: "Brasil",
  BRN: "Brunei",
  BGR: "Bulgaria",
  BFA: "Burkina Faso",
  BDI: "Burundi",
  CAN: "Canada",
  CYM: "Caymanøyene",
  CHL: "Chile",
  CXR: "Christmasøya",
  COL: "Colombia",
  COK: "Cookøyene",
  CRI: "Costa Rica",
  CUB: "Cuba",
  CUW: "Curaçao",
  DNK: "Danmark",
  ARE: "De forente arabiske emirater",
  ATF: "De franske sørterritorier",
  PSE: "De palestinske territoriene",
  DOM: "Den dominikanske republikk",
  CAF: "Den sentralafrikanske republikk",
  IOT: "Det britiske territoriet i Indiahavet",
  DJI: "Djibouti",
  DMA: "Dominica",
  ECU: "Ecuador",
  EGY: "Egypt",
  GNQ: "Ekvatorial-Guinea",
  CIV: "Elfenbenskysten",
  SLV: "El Salvador",
  ERI: "Eritrea",
  EST: "Estland",
  ETH: "Etiopia",
  FLK: "Falklandsøyene",
  FJI: "Fiji",
  PHL: "Filippinene",
  FIN: "Finland",
  FRA: "Frankrike",
  GUF: "Fransk Guyana",
  PYF: "Fransk Polynesia",
  FRO: "Færøyene",
  GAB: "Gabon",
  GMB: "Gambia",
  GEO: "Georgia",
  GHA: "Ghana",
  GIB: "Gibraltar",
  GRD: "Grenada",
  GRL: "Grønland",
  GLP: "Guadeloupe",
  GUM: "Guam",
  GTM: "Guatemala",
  GGY: "Guernsey",
  GIN: "Guinea",
  GNB: "Guinea-Bissau",
  GUY: "Guyana",
  HTI: "Haiti",
  HMD: "Heard- og McDonaldøyene",
  GRC: "Hellas",
  HND: "Honduras",
  HKG: "Hongkong",
  BLR: "Hviterussland",
  IND: "India",
  IDN: "Indonesia",
  IRQ: "Irak",
  IRN: "Iran",
  IRL: "Irland",
  ISL: "Island",
  ISR: "Israel",
  ITA: "Italia",
  JAM: "Jamaica",
  JPN: "Japan",
  YEM: "Jemen",
  JEY: "Jersey",
  VIR: "Jomfruøyene, De amerikanske",
  VGB: "Jomfruøyene, De britiske",
  JOR: "Jordan",
  KHM: "Kambodsja",
  CMR: "Kamerun",
  CPV: "Kapp Verde",
  KAZ: "Kasakhstan",
  KEN: "Kenya",
  CHN: "Kina",
  KGZ: "Kirgisistan",
  KIR: "Kiribati",
  CCK: "Kokosøyene",
  COM: "Komorene",
  COD: "Kongo, Den demokratiske republikken",
  COG: "Kongo, Republikken",
  HRV: "Kroatia",
  KWT: "Kuwait",
  CYP: "Kypros",
  LAO: "Laos",
  LVA: "Latvia",
  LSO: "Lesotho",
  LBN: "Libanon",
  LBR: "Liberia",
  LBY: "Libya",
  LIE: "Liechtenstein",
  LTU: "Litauen",
  LUX: "Luxembourg",
  MAC: "Macao",
  MDG: "Madagaskar",
  MWI: "Malawi",
  MYS: "Malaysia",
  MDV: "Maldivene",
  MLI: "Mali",
  MLT: "Malta",
  IMN: "Man",
  MAR: "Marokko",
  MHL: "Marshalløyene",
  MTQ: "Martinique",
  MRT: "Mauritania",
  MUS: "Mauritius",
  MYT: "Mayotte",
  MEX: "Mexico",
  FSM: "Mikronesiaføderasjonen",
  MDA: "Moldova",
  MCO: "Monaco",
  MNG: "Mongolia",
  MNE: "Montenegro",
  MSR: "Montserrat",
  MOZ: "Mosambik",
  MMR: "Myanmar",
  NAM: "Namibia",
  NRU: "Nauru",
  NPL: "Nepal",
  NLD: "Nederland",
  NZL: "New Zealand",
  NIC: "Nicaragua",
  NER: "Niger",
  NGA: "Nigeria",
  NIU: "Niue",
  PRK: "Nord-Korea",
  MKD: "Nord-Makedonia, Republikken",
  MNP: "Nord-Marianene",
  NFK: "Norfolkøya",
  NOR: "Norge",
  NCL: "Ny-Caledonia",
  OMN: "Oman",
  PAK: "Pakistan",
  PLW: "Palau",
  PAN: "Panama",
  PNG: "Papua Ny-Guinea",
  PRY: "Paraguay",
  PER: "Peru",
  PCN: "Pitcairnøyene",
  POL: "Polen",
  PRT: "Portugal",
  PRI: "Puerto Rico",
  QAT: "Qatar",
  REU: "Réunion",
  ROU: "Romania",
  RUS: "Russland",
  RWA: "Rwanda",
  BLM: "Saint-Barthélemy",
  SHN: "St. Helena, Ascension og Tristan da Cunha",
  KNA: "Saint Kitts og Nevis",
  LCA: "Saint Lucia",
  MAF: "Saint-Martin",
  SPM: "Saint-Pierre og Miquelon",
  VCT: "Saint Vincent og Grenadinene",
  SLB: "Salomonøyene",
  WSM: "Samoa",
  SMR: "San Marino",
  STP: "São Tomé og Príncipe",
  SAU: "Saudi-Arabia",
  SEN: "Senegal",
  SRB: "Serbia",
  SYC: "Seychellene",
  SLE: "Sierra Leone",
  SGP: "Singapore",
  SXM: "Sint Maarten",
  SVK: "Slovakia",
  SVN: "Slovenia",
  SOM: "Somalia",
  ESP: "Spania",
  LKA: "Sri Lanka",
  GBR: "Storbritannia",
  SDN: "Sudan",
  SUR: "Surinam",
  SJM: "Svalbard og Jan Mayen",
  CHE: "Sveits",
  SWE: "Sverige",
  SWZ: "Eswatini",
  SYR: "Syria",
  ZAF: "Sør-Afrika",
  SGS: "Sør-Georgia og Sør-Sandwichøyene",
  KOR: "Sør-Korea",
  SSD: "Sør-Sudan",
  TJK: "Tadsjikistan",
  TWN: "Taiwan",
  TZA: "Tanzania",
  THA: "Thailand",
  TGO: "Togo",
  TKL: "Tokelau",
  TON: "Tonga",
  TTO: "Trinidad og Tobago",
  TCD: "Tsjad",
  CZE: "Tsjekkia",
  TUN: "Tunisia",
  TKM: "Turkmenistan",
  TCA: "Turks- og Caicosøyene",
  TUV: "Tuvalu",
  TUR: "Tyrkia",
  DEU: "Tyskland",
  UGA: "Uganda",
  UKR: "Ukraina",
  HUN: "Ungarn",
  URY: "Uruguay",
  USA: "USA",
  UMI: "USAs ytre småøyer",
  UZB: "Usbekistan",
  VUT: "Vanuatu",
  VAT: "Vatikanstaten",
  VEN: "Venezuela",
  ESH: "Vest-Sahara",
  VNM: "Vietnam",
  WLF: "Wallis- og Futunaøyene",
  ZMB: "Zambia",
  ZWE: "Zimbabwe",
  TLS: "Øst-Timor",
  ALA: "Åland",
};

export function hentNorskLandnavn(isoA3Kode?: string): string | undefined {
  return isoA3Kode ? (norwegianCountryNames[isoA3Kode.toUpperCase()] ?? isoA3Kode) : isoA3Kode;
}
