import { http, HttpResponse } from "msw";
import { mockBehandling } from "./data/mock-behandling";

export const mockDpBehandling = [
  http.get(`${process.env.DP_BEHANDLING_URL}/behandling/:behandlingId`, () => {
    return HttpResponse.json(mockBehandling);
    // return HttpResponse.json(
    //   {
    //     type: "A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type",
    //     title:
    //       "A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization",
    //     status:
    //       "The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem",
    //     detail:
    //       "A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced",
    //     instance:
    //       "A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced",
    //   },
    //   { status: 400 },
    // );
  }),

  http.post(`${process.env.DP_BEHANDLING_URL}/behandling/:behandlingId/avbryt`, () => {
    return new HttpResponse(null, {
      status: 201,
    });
  }),

  http.post(`${process.env.DP_BEHANDLING_URL}/behandling/:behandlingId/godkjenn`, () => {
    return new HttpResponse(null, {
      status: 201,
    });
  }),

  http.put(
    `${process.env.DP_BEHANDLING_URL}/behandling/:behandlingId/opplysning/:opplysningId`,
    () => {
      return HttpResponse.json(mockBehandling);
    },
  ),
];
