import type { IVilkaar } from "~/models/Vilkaar.server";
import type { Faktum } from "~/models/faktum.server";
import type { IGeneratorFaktum } from "~/models/faktum.server";

const reellArbeidsokerFakta: (Faktum | IGeneratorFaktum)[] = [
  {
    id: "1",
    svar: true,
    type: "boolean",
    roller: ["søker"],
    readOnly: false,
    gyldigeValg: ["faktum.jobbe-hel-deltid.svar.ja", "faktum.jobbe-hel-deltid.svar.nei"],
    beskrivendeId: "faktum.jobbe-hel-deltid",
    sannsynliggjoresAv: [],
  },
  {
    id: "5",
    svar: true,
    type: "boolean",
    roller: ["søker"],
    readOnly: false,
    gyldigeValg: ["faktum.jobbe-hele-norge.svar.ja", "faktum.jobbe-hele-norge.svar.nei"],
    beskrivendeId: "faktum.jobbe-hele-norge",
    sannsynliggjoresAv: [],
  },
  {
    id: "8",
    svar: false,
    type: "boolean",
    roller: ["søker"],
    readOnly: false,
    gyldigeValg: ["faktum.alle-typer-arbeid.svar.ja", "faktum.alle-typer-arbeid.svar.nei"],
    beskrivendeId: "faktum.alle-typer-arbeid",
    sannsynliggjoresAv: [
      // {
      //   id: "10",
      //   type: "dokument",
      //   roller: ["søker"],
      //   readOnly: true,
      //   beskrivendeId: "faktum.dokument-bekreftelse-fra-lege-eller-annen-behandler",
      //   sannsynliggjoresAv: [],
      // },
    ],
  },
  {
    id: "9",
    svar: true,
    type: "boolean",
    roller: ["søker"],
    readOnly: false,
    gyldigeValg: ["faktum.bytte-yrke-ned-i-lonn.svar.ja", "faktum.bytte-yrke-ned-i-lonn.svar.nei"],
    beskrivendeId: "faktum.bytte-yrke-ned-i-lonn",
    sannsynliggjoresAv: [],
  },
];

const arbeidsforholdFakta: (Faktum | IGeneratorFaktum)[] = [
  {
    id: "101",
    svar: "faktum.mottatt-dagpenger-siste-12-mnd.svar.nei",
    type: "envalg",
    roller: ["søker"],
    readOnly: false,
    gyldigeValg: [
      "faktum.mottatt-dagpenger-siste-12-mnd.svar.ja",
      "faktum.mottatt-dagpenger-siste-12-mnd.svar.nei",
      "faktum.mottatt-dagpenger-siste-12-mnd.svar.vet-ikke",
    ],
    beskrivendeId: "faktum.mottatt-dagpenger-siste-12-mnd",
    sannsynliggjoresAv: [],
  },
  {
    id: "108",
    svar: "2023-03-04",
    type: "localdate",
    roller: ["søker"],
    readOnly: false,
    beskrivendeId: "faktum.dagpenger-soknadsdato",
    sannsynliggjoresAv: [],
  },
  {
    id: "107",
    svar: "faktum.type-arbeidstid.svar.fast",
    type: "envalg",
    roller: ["søker"],
    readOnly: false,
    gyldigeValg: [
      "faktum.type-arbeidstid.svar.fast",
      "faktum.type-arbeidstid.svar.varierende",
      "faktum.type-arbeidstid.svar.kombinasjon",
      "faktum.type-arbeidstid.svar.ingen-passer",
    ],
    beskrivendeId: "faktum.type-arbeidstid",
    sannsynliggjoresAv: [],
  },
  {
    id: "109",
    svar: [
      [
        {
          id: "110.1",
          svar: "Remen 100",
          type: "tekst",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.arbeidsforhold.navn-bedrift",
          sannsynliggjoresAv: [],
        },
        {
          id: "111.1",
          svar: "NOR",
          type: "land",
          roller: ["søker"],
          grupper: [],
          readOnly: false,
          gyldigeLand: [
            "AFG",
            "ALA",
            "ALB",
            "DZA",
            "ASM",
            "AND",
            "AGO",
            "AIA",
            "ATA",
            "ATG",
            "ARG",
            "ARM",
            "ABW",
            "AUS",
            "AUT",
            "AZE",
            "BHS",
            "BHR",
            "BGD",
            "BRB",
            "BLR",
            "BEL",
            "BLZ",
            "BEN",
            "BMU",
            "BTN",
            "BOL",
            "BES",
            "BIH",
            "BWA",
            "BVT",
            "BRA",
            "IOT",
            "BRN",
            "BGR",
            "BFA",
            "BDI",
            "KHM",
            "CMR",
            "CAN",
            "CPV",
            "CYM",
            "CAF",
            "TCD",
            "CHL",
            "CHN",
            "CXR",
            "CCK",
            "COL",
            "COM",
            "COG",
            "COD",
            "COK",
            "CRI",
            "CIV",
            "HRV",
            "CUB",
            "CUW",
            "CYP",
            "CZE",
            "DNK",
            "DJI",
            "DMA",
            "DOM",
            "ECU",
            "EGY",
            "SLV",
            "GNQ",
            "ERI",
            "EST",
            "ETH",
            "FLK",
            "FRO",
            "FJI",
            "FIN",
            "FRA",
            "GUF",
            "PYF",
            "ATF",
            "GAB",
            "GMB",
            "GEO",
            "DEU",
            "GHA",
            "GIB",
            "GRC",
            "GRL",
            "GRD",
            "GLP",
            "GUM",
            "GTM",
            "GGY",
            "GIN",
            "GNB",
            "GUY",
            "HTI",
            "HMD",
            "VAT",
            "HND",
            "HKG",
            "HUN",
            "ISL",
            "IND",
            "IDN",
            "IRN",
            "IRQ",
            "IRL",
            "IMN",
            "ISR",
            "ITA",
            "JAM",
            "JPN",
            "JEY",
            "JOR",
            "KAZ",
            "KEN",
            "KIR",
            "PRK",
            "KOR",
            "KWT",
            "KGZ",
            "LAO",
            "LVA",
            "LBN",
            "LSO",
            "LBR",
            "LBY",
            "LIE",
            "LTU",
            "LUX",
            "MAC",
            "MKD",
            "MDG",
            "MWI",
            "MYS",
            "MDV",
            "MLI",
            "MLT",
            "MHL",
            "MTQ",
            "MRT",
            "MUS",
            "MYT",
            "MEX",
            "FSM",
            "MAR",
            "MDA",
            "MCO",
            "MNG",
            "MNE",
            "MSR",
            "MOZ",
            "MMR",
            "NAM",
            "NRU",
            "NPL",
            "NLD",
            "NCL",
            "NZL",
            "NIC",
            "NER",
            "NGA",
            "NIU",
            "NFK",
            "MNP",
            "NOR",
            "OMN",
            "PAK",
            "PLW",
            "PSE",
            "PAN",
            "PNG",
            "PRY",
            "PER",
            "PHL",
            "PCN",
            "POL",
            "PRT",
            "PRI",
            "QAT",
            "REU",
            "ROU",
            "RUS",
            "RWA",
            "BLM",
            "SHN",
            "KNA",
            "LCA",
            "MAF",
            "SPM",
            "VCT",
            "WSM",
            "SMR",
            "STP",
            "SAU",
            "SEN",
            "SRB",
            "SYC",
            "SLE",
            "SGP",
            "SXM",
            "SVK",
            "SVN",
            "SLB",
            "SOM",
            "ZAF",
            "SGS",
            "SSD",
            "ESP",
            "LKA",
            "SDN",
            "SUR",
            "SJM",
            "SWZ",
            "SWE",
            "CHE",
            "SYR",
            "TWN",
            "TJK",
            "TZA",
            "THA",
            "TLS",
            "TGO",
            "TKL",
            "TON",
            "TTO",
            "TUN",
            "TUR",
            "TKM",
            "TCA",
            "TUV",
            "UGA",
            "UKR",
            "ARE",
            "GBR",
            "USA",
            "UMI",
            "URY",
            "UZB",
            "VUT",
            "VEN",
            "VNM",
            "VGB",
            "VIR",
            "WLF",
            "ESH",
            "YEM",
            "ZMB",
            "ZWE",
          ],
          beskrivendeId: "faktum.arbeidsforhold.land",
          sannsynliggjoresAv: [],
        },
        {
          id: "112.1",
          svar: "faktum.arbeidsforhold.endret.svar.sagt-opp-av-arbeidsgiver",
          type: "envalg",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.arbeidsforhold.endret.svar.ikke-endret",
            "faktum.arbeidsforhold.endret.svar.avskjediget",
            "faktum.arbeidsforhold.endret.svar.sagt-opp-av-arbeidsgiver",
            "faktum.arbeidsforhold.endret.svar.arbeidsgiver-konkurs",
            "faktum.arbeidsforhold.endret.svar.kontrakt-utgaatt",
            "faktum.arbeidsforhold.endret.svar.sagt-opp-selv",
            "faktum.arbeidsforhold.endret.svar.redusert-arbeidstid",
            "faktum.arbeidsforhold.endret.svar.permittert",
          ],
          beskrivendeId: "faktum.arbeidsforhold.endret",
          sannsynliggjoresAv: [
            {
              id: "155.1",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              generertAv: "Remen 100",
              beskrivendeId: "faktum.dokument-arbeidsavtale",
              sannsynliggjoresAv: [],
            },
            {
              id: "157.1",
              type: "dokument",
              roller: ["søker"],
              readOnly: true,
              generertAv: "Remen 100",
              beskrivendeId: "faktum.dokument-arbeidsforhold-blitt-sagt-opp",
              sannsynliggjoresAv: [],
            },
          ],
        },
        {
          id: "123.1",
          svar: {
            fom: "2019-03-01",
            tom: "2019-03-01",
          },
          type: "periode",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.arbeidsforhold.varighet",
          sannsynliggjoresAv: [],
        },
        {
          id: "124.1",
          svar: false,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.arbeidsforhold.vet-du-antall-timer-foer-mistet-jobb.svar.ja",
            "faktum.arbeidsforhold.vet-du-antall-timer-foer-mistet-jobb.svar.nei",
          ],
          beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-mistet-jobb",
          sannsynliggjoresAv: [],
        },
        {
          id: "147.1",
          svar: "Slåss med pølsemakeren",
          type: "tekst",
          roller: ["søker"],
          readOnly: false,
          beskrivendeId: "faktum.arbeidsforhold.vet-du-aarsak-til-sagt-opp-av-arbeidsgiver",
          sannsynliggjoresAv: [],
        },
        {
          id: "150.1",
          svar: true,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.arbeidsforhold.tilbud-om-annen-stilling-eller-annet-sted-i-norge.svar.ja",
            "faktum.arbeidsforhold.tilbud-om-annen-stilling-eller-annet-sted-i-norge.svar.nei",
          ],
          beskrivendeId: "faktum.arbeidsforhold.tilbud-om-annen-stilling-eller-annet-sted-i-norge",
          sannsynliggjoresAv: [],
        },
        {
          id: "151.1",
          svar: false,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.arbeidsforhold.skift-eller-turnus.svar.ja",
            "faktum.arbeidsforhold.skift-eller-turnus.svar.nei",
          ],
          beskrivendeId: "faktum.arbeidsforhold.skift-eller-turnus",
          sannsynliggjoresAv: [],
        },
        {
          id: "152.1",
          svar: false,
          type: "boolean",
          roller: ["søker"],
          readOnly: false,
          gyldigeValg: [
            "faktum.arbeidsforhold.rotasjon.svar.ja",
            "faktum.arbeidsforhold.rotasjon.svar.nei",
          ],
          beskrivendeId: "faktum.arbeidsforhold.rotasjon",
          sannsynliggjoresAv: [],
        },
      ],
    ],
    type: "generator",
    roller: ["søker"],
    readOnly: false,
    templates: [
      {
        id: "110",
        type: "tekst",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.navn-bedrift",
      },
      {
        id: "111",
        type: "land",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.land",
      },
      {
        id: "112",
        type: "envalg",
        roller: ["søker"],
        gyldigeValg: [
          "faktum.arbeidsforhold.endret.svar.ikke-endret",
          "faktum.arbeidsforhold.endret.svar.avskjediget",
          "faktum.arbeidsforhold.endret.svar.sagt-opp-av-arbeidsgiver",
          "faktum.arbeidsforhold.endret.svar.arbeidsgiver-konkurs",
          "faktum.arbeidsforhold.endret.svar.kontrakt-utgaatt",
          "faktum.arbeidsforhold.endret.svar.sagt-opp-selv",
          "faktum.arbeidsforhold.endret.svar.redusert-arbeidstid",
          "faktum.arbeidsforhold.endret.svar.permittert",
        ],
        beskrivendeId: "faktum.arbeidsforhold.endret",
      },
      {
        id: "113",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.kjent-antall-timer-jobbet",
      },
      {
        id: "114",
        type: "double",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.antall-timer-jobbet",
      },
      {
        id: "115",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.har-tilleggsopplysninger",
      },
      {
        id: "116",
        type: "tekst",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.tilleggsopplysninger",
      },
      {
        id: "117",
        type: "localdate",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.startdato-arbeidsforhold",
      },
      {
        id: "118",
        type: "localdate",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.arbeidstid-redusert-fra-dato",
      },
      {
        id: "119",
        type: "envalg",
        roller: ["søker"],
        gyldigeValg: [
          "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato.svar.ja",
          "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato.svar.nei",
          "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato.svar.vet-ikke",
        ],
        beskrivendeId: "faktum.arbeidsforhold.midlertidig-med-kontraktfestet-sluttdato",
      },
      {
        id: "120",
        type: "localdate",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.kontraktfestet-sluttdato",
      },
      {
        id: "121",
        type: "localdate",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.midlertidig-arbeidsforhold-oppstartsdato",
      },
      {
        id: "122",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.permittertert-fra-fiskeri-naering",
      },
      {
        id: "123",
        type: "periode",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.varighet",
      },
      {
        id: "149",
        type: "envalg",
        roller: ["søker"],
        gyldigeValg: [
          "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato.svar.ja",
          "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato.svar.nei",
          "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato.svar.vet-ikke",
        ],
        beskrivendeId: "faktum.arbeidsforhold.midlertidig-arbeidsforhold-med-sluttdato",
      },
      {
        id: "124",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-mistet-jobb",
      },
      {
        id: "125",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-konkurs",
      },
      {
        id: "126",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-kontrakt-utgikk",
      },
      {
        id: "127",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-du-sa-opp",
      },
      {
        id: "128",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-redusert-arbeidstid",
      },
      {
        id: "129",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.vet-du-antall-timer-foer-permittert",
      },
      {
        id: "130",
        type: "double",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.antall-timer-dette-arbeidsforhold",
      },
      {
        id: "131",
        type: "periode",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.permittert-periode",
      },
      {
        id: "132",
        type: "int",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.permittert-prosent",
      },
      {
        id: "133",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.vet-du-lonnsplikt-periode",
      },
      {
        id: "134",
        type: "periode",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.naar-var-lonnsplikt-periode",
      },
      {
        id: "135",
        type: "tekst",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.aarsak-til-du-sa-opp",
      },
      {
        id: "136",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.tilbud-om-forlengelse-eller-annen-stilling",
      },
      {
        id: "137",
        type: "envalg",
        roller: ["søker"],
        gyldigeValg: [
          "faktum.arbeidsforhold.svar-paa-forlengelse-eller-annen-stilling.svar.ja",
          "faktum.arbeidsforhold.svar-paa-forlengelse-eller-annen-stilling.svar.nei",
          "faktum.arbeidsforhold.svar-paa-forlengelse-eller-annen-stilling.svar.ikke-svart",
        ],
        beskrivendeId: "faktum.arbeidsforhold.svar-paa-forlengelse-eller-annen-stilling",
      },
      {
        id: "138",
        type: "tekst",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.aarsak-til-ikke-akseptert-tilbud",
      },
      {
        id: "139",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.soke-forskudd-lonnsgarantimidler",
      },
      {
        id: "140",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId:
          "faktum.arbeidsforhold.soke-forskudd-lonnsgarantimidler-i-tillegg-til-dagpenger",
      },
      {
        id: "164",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.godta-trekk-fra-konkursbo",
      },
      {
        id: "141",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId:
          "faktum.arbeidsforhold.godta-trekk-fra-nav-av-forskudd-fra-lonnsgarantimidler",
      },
      {
        id: "142",
        type: "envalg",
        roller: ["søker"],
        gyldigeValg: [
          "faktum.arbeidsforhold.har-sokt-om-lonnsgarantimidler.svar.nei",
          "faktum.arbeidsforhold.har-sokt-om-lonnsgarantimidler.svar.nei-men-skal",
          "faktum.arbeidsforhold.har-sokt-om-lonnsgarantimidler.svar.ja",
        ],
        beskrivendeId: "faktum.arbeidsforhold.har-sokt-om-lonnsgarantimidler",
      },
      {
        id: "143",
        type: "envalg",
        roller: ["søker"],
        gyldigeValg: [
          "faktum.arbeidsforhold.dekker-lonnsgarantiordningen-lonnskravet-ditt.svar.ja",
          "faktum.arbeidsforhold.dekker-lonnsgarantiordningen-lonnskravet-ditt.svar.nei",
          "faktum.arbeidsforhold.dekker-lonnsgarantiordningen-lonnskravet-ditt.svar.vet-ikke",
        ],
        beskrivendeId: "faktum.arbeidsforhold.dekker-lonnsgarantiordningen-lonnskravet-ditt",
      },
      {
        id: "144",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.utbetalt-lonn-etter-konkurs",
      },
      {
        id: "145",
        type: "localdate",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.siste-dag-utbetalt-for-konkurs",
      },
      {
        id: "146",
        type: "tekst",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.hva-er-aarsak-til-avskjediget",
      },
      {
        id: "147",
        type: "tekst",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.vet-du-aarsak-til-sagt-opp-av-arbeidsgiver",
      },
      {
        id: "148",
        type: "tekst",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.vet-du-aarsak-til-redusert-arbeidstid",
      },
      {
        id: "150",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.tilbud-om-annen-stilling-eller-annet-sted-i-norge",
      },
      {
        id: "151",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.skift-eller-turnus",
      },
      {
        id: "152",
        type: "boolean",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.rotasjon",
      },
      {
        id: "153",
        type: "int",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.arbeidsdager-siste-rotasjon",
      },
      {
        id: "154",
        type: "int",
        roller: ["søker"],
        beskrivendeId: "faktum.arbeidsforhold.fridager-siste-rotasjon",
      },
      {
        id: "155",
        type: "dokument",
        roller: ["søker"],
        beskrivendeId: "faktum.dokument-arbeidsavtale",
      },
      {
        id: "156",
        type: "dokument",
        roller: ["søker"],
        beskrivendeId: "faktum.dokument-arbeidsforhold-avskjediget",
      },
      {
        id: "157",
        type: "dokument",
        roller: ["søker"],
        beskrivendeId: "faktum.dokument-arbeidsforhold-blitt-sagt-opp",
      },
      {
        id: "158",
        type: "dokument",
        roller: ["søker"],
        beskrivendeId: "faktum.dokument-timelister",
      },
      {
        id: "159",
        type: "dokument",
        roller: ["søker"],
        beskrivendeId: "faktum.dokument-brev-fra-bobestyrer-eller-konkursforvalter",
      },
      {
        id: "160",
        type: "dokument",
        roller: ["søker"],
        beskrivendeId: "faktum.dokument-arbeidsforhold-sagt-opp-selv",
      },
      {
        id: "161",
        type: "dokument",
        roller: ["søker"],
        beskrivendeId: "faktum.dokument-arbeidsforhold-redusert",
      },
      {
        id: "162",
        type: "dokument",
        roller: ["søker"],
        beskrivendeId: "faktum.dokument-arbeidsforhold-permittert",
      },
    ],
    beskrivendeId: "faktum.arbeidsforhold",
  },
];

export const mockVilkaar: IVilkaar[] = [
  {
    id: "1",
    navn: "Reell arbeidsøker",
    fakta: reellArbeidsokerFakta,
    status: "Manuell",
  },
  {
    id: "2",
    navn: "Ikke over 67 år",
    fakta: [],
    status: "Godkjent",
  },
  {
    id: "3",
    navn: "Arbeidssøker",
    fakta: arbeidsforholdFakta,
    status: "Avslag",
  },
];
